blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('posts.urls', namespace="posts")),
]

posts/urls.py
from django.conf.urls import url
from . import views
from .views import PostDetailView

urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^(?P<pk>\d+)/$', PostDetailView.as_view()),
    url(r'^edit/$', views.edit, name='edit'),
    url(r'^edit/done/$', views.add, name='done'),
] 

posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(u'Зоголовок поста', max_length=150)
    content = models.TextField(u'Контент', blank=True)
    published = models.BooleanField(u'Опубликовано', default=False)


def __unicode__(self):
        return self.title

def get_absolute_url(self):
        return "posts/%i/" % self.id

posts/forms.py
from django import forms

class AddPost(forms.Form):
    title = forms.CharField(max_length=100)
    content = forms.CharField(max_length=1000, required=False, widget=forms.Textarea)

posts/views.py
from django.shortcuts import render, render_to_response
from .models import Post
from .forms import AddPost
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView



class PostDetailView(DetailView):
    model = Post


def posts(request):
    posts_list = Post.objects.all()
    paginator = Paginator(posts_list, 2)
    page = request.GET.get('page')
    try:
        posts_pag = paginator.page(page)
    except PageNotAnInteger:
        posts_pag = paginator.page(1)
    except EmptyPage:
        posts_pag = paginator.page(paginator.num_pages)
    context = {'posts': posts_list,
               'pag': posts_pag, }
    return render_to_response('posts/posts.html', context)


def edit(request):
    form = AddPost()
    return render(request, 'posts/edit.html', {'form': form})


def add(request):
    if request.method == 'POST':
        form = AddPost(request.POST)
        if form.is_valid():
            p = Post()
            p.title = form.cleaned_data['title']
            p.content = form.cleaned_data['content']
            p.save()
            return HttpResponseRedirect(reverse('posts:posts'))
    else:
        form = AddPost()
    return render(request, 'posts/edit.html', {'form': form})


def custom_404(request):
    return render(request, '404.html')


def custom_500(request):
    return render(request, '500.html')


def publish(post_id):
    p = Post.objects.get(id=post_id)
    p.published = True
    p.save()

posts/templates/posts/edit.html
{% extends "base.html" %}
{% block title %}Add new post{% endblock %}
{% block heading %}Add new post{% endblock %}
{% block sidebar %}{% endblock %}
{% block content %}
<form action="{% url 'posts:done' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add new post">
</form>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>{{ post.title|upper }}</h2>
    <p>{{ post.content|lower }}</p>
{% endblock %}

posts/templates/posts/posts.html
{% extends "base.html" %}
{% block title %}Posts{% endblock %}
{% block heading %}Posts{% endblock %}
{% block content %}
{% for post in pag.object_list %}
        <h2 {% if post.published = True %}style="color:green;"{% endif %}>{{ post.title|upper }}</h2>
        <p>{{ post.content|lower|cut:"а"|linenumbers }}</p>
    {% empty %}
    <p>No posts yet</p>
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if pag.has_previous %}
            <a href="?page={{ pag.previous_page_number }}">Previous</a>
        {% endif %}

        <span class="current">
            Page {{ pag.number|center:"4" }} of {{ pag.paginator.num_pages|add:"1" }}
        </span>

        {% if pag.has_next %}
            <a href="?page={{ pag.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div><br>

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load cache %}
<html lang="en">
<head>
    <meta charset="utf-8">
    {% load staticfiles %}
    {% block style_css %}<link rel="stylesheet" href="{% static 'style.css' %}" />{% endblock %}
<title>{% block title %}Le blogue{% endblock %}</title>
</head>
<body>
    <div id="heading"><h1>{% block heading %}Le blogue{% endblock %}</h1></div>
 <div id="sidebar">
    {% cache 500 sidebar %}
    {% block sidebar %}
    <ul>
        <li><a href="{% url 'posts:posts' %}">Posts</a></li>
        <li><a href="{% url 'posts:edit' %}">Add Posts</a></li>
        <li><a href="/contacts/">Contacts</a></li>
    </ul>
     {% endblock %}
     {% endcache %}
 </div>
 <div id="content">
     {% block content %}{% endblock %}
     {% comment %} Приминение тега комментария {% endcomment %}
 </div>
</body>
</html>